name: learn-github-actions
on: [push]
jobs:
  call-continuous-integration-reusable:
    uses: anand-320/github-reusable-workflows/.github/workflows/ci.yml@main
    with:
      project_name: expense-backend
    secrets: inherit
