name: continuous integration
on:
  push:
    branches:
      - main
      - 'EXP-**'
  call-continuous-integration-reusable:
    uses: anand-320/github-reusable-workflows/.github/workflows/ci.yml@main
    with:
      project_name: expense-backend
      npm_install: true
    secrets: inherit

